### ISSUE TITLE
proble with dnase-seq peaks mapped in reverse strands

### ISSUE THREAD

**Issue by fransua** [Jstacs/Jstacs#2]
Hi,
first thanks for the tools, and the tutorial!

I am having troubles with a couple of DNAse-seq BAM files (here an example: https://www.encodeproject.org/experiments/ENCSR136DNA/)

Catchitt throws this error message:

```
$ java -jar Catchitt.jar access i=/mnt/MareNostrum/db/dnase_seq/ENCFF473YHH.bam b=100 outdir=dnase

Parameters of tool "Chromatin accessibility" (access, version: 0.1):
d - Data source (The format of the input file containing the coverage information, range={BAM/SAM, Bigwig}, default = BAM/SAM)  = BAM/SAM
    Parameters for selection "BAM/SAM":
        i - Input SAM/BAM (The input file containing the mapped DNase-seq/ATAC-seq reads)       = /mnt/MareNostrum/db/dnase_seq/ENCFF473YHH.bam
    Parameters for selection "Bigwig":
        i - Input Bigwig (The input file containing the mapped DNase-seq/ATAC-seq reads)        = null
        f - FastA index (The genome index)      = null
b - Bin width (The width of the genomic bins considered)        = 100
outdir - The output directory, defaults to the current working directory (.)    = dnase
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: Index -84668 out of bounds for length 10000
        at projects.encodedream.Pileup.pileup(Pileup.java:299)
        at projects.encodedream.tools.ChromatinAccessibility.lambda$0(ChromatinAccessibility.java:93)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I believe that this happens because of the strand on which the read is mapped, for instance if I convert all revert strands to forward, by changing BAM flags, it works.

_EDIT: this behavior also occurs when sequence length is negative_

thanks!

**Comment by jgraux** [comment]
This issue should have been fixed already in the github version. I just released a new binary version at http://jstacs.de/index.php/Catchitt, and would be grateful if you could test it.

**Comment by fransua** [comment]
Hi @jgraux 
it's working!

thanks for the support!

**Comment by fransua** [comment]
wups... I should have waited a bit before sorry...
it seems that the predict part is broken now:

```
 ➤  java -jar Catchitt.jar predict c=Classifiers.xml a=Chromatin_accessibility.tsv.gz m=Motif_scores.1.tsv.gz m=Motif_scores.2.tsv.gz m=Motif_scores.3.tsv.gz f=Homo_sapiens-GRCh38.p13.fa.fai abb=1 aba=4 n=3 outdir=tmp                                                                                                     

Parameters of tool "Prediction" (predict, version: 0.1):
c - Classifiers (The classifiers trained by iterative training, mime = xml)     = Classifiers.xml
a - Accessibility (File containing accessibility features, mime = tsv.gz)       = Chromatin_accessibility.tsv.gz
        The following parameter(s) can be used multiple times:
        m (1) - Motif (File containing motif features, mime = tsv.gz)   = Motif_scores.1.tsv.gz
        m (2) - Motif (File containing motif features, mime = tsv.gz)   = Motif_scores.2.tsv.gz
        m (3) - Motif (File containing motif features, mime = tsv.gz)   = Motif_scores.3.tsv.gz
f - FAI of genome (FastA index file of the genome, mime = fai)  = Homo_sapiens-GRCh38.p13.fa.fai
p - Prediction chromosomes (Prediction chromosomes, separated by commas, OPTIONAL)      = null
abb - Aggregation: bins before (Number of bins before the current one considered for aggregation., OPTIONAL)    = 1
aba - Aggregation: bins after (Number of bins after the current one considered for aggregation., OPTIONAL)      = 4
n - Number of classifiers (Use only the first k (last k for negative values) classifiers for predictions., OPTIONAL)    = 3
outdir - The output directory, defaults to the current working directory (.)    = tmp
Exception in thread "main" de.jstacs.io.NonParsableException: StringBuffer not parsable. (problem at projects.encodedream.ClassifiersWithInfo: InvocationTargetException: de.jstacs.io.NonParsableException: StringBuffer not parsable. (problem at de.jstacs.classifiers.differentiableSequenceScoreBased.gendismix.GenDisMixC
lassifier: InvocationTargetException: de.jstacs.io.NonParsableException: StringBuffer not parsable. (problem at de.jstacs.sequenceScores.statisticalModels.differentiable.continuous.GaussianNetwork: InvocationTargetException: de.jstacs.io.NonParsableException: StringBuffer not parsable. (Could not find "ess".)        

-- de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:692)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  de.jstacs.sequenceScores.statisticalModels.differentiable.continuous.GaussianNetwork.fromXML(GaussianNetwork.java:354)
--  de.jstacs.sequenceScores.differentiable.AbstractDifferentiableSequenceScore.<init>(AbstractDifferentiableSequenceScore.java:120)
--  de.jstacs.sequenceScores.statisticalModels.differentiable.AbstractDifferentiableStatisticalModel.<init>(AbstractDifferentiableStatisticalModel.java:67)
--  de.jstacs.sequenceScores.statisticalModels.differentiable.continuous.GaussianNetwork.<init>(GaussianNetwork.java:132)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:728)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)                                                                                                                                                                                                                                              
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)                                                                                                                                                                                                                                      [57/2217]
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  de.jstacs.classifiers.differentiableSequenceScoreBased.ScoreClassifier.extractFurtherClassifierInfosFromXML(ScoreClassifier.java:499)
--  de.jstacs.classifiers.differentiableSequenceScoreBased.gendismix.GenDisMixClassifier.extractFurtherClassifierInfosFromXML(GenDisMixClassifier.java:283)
--  de.jstacs.classifiers.AbstractClassifier.fromXML(AbstractClassifier.java:513)
--  de.jstacs.classifiers.AbstractClassifier.<init>(AbstractClassifier.java:123)
--  de.jstacs.classifiers.AbstractScoreBasedClassifier.<init>(AbstractScoreBasedClassifier.java:165)
--  de.jstacs.classifiers.differentiableSequenceScoreBased.ScoreClassifier.<init>(ScoreClassifier.java:151)
--  de.jstacs.classifiers.differentiableSequenceScoreBased.gendismix.GenDisMixClassifier.<init>(GenDisMixClassifier.java:198)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:728)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  projects.encodedream.ClassifiersWithInfo.<init>(ClassifiersWithInfo.java:43)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  projects.encodedream.tools.PredictionTool.run(PredictionTool.java:86)
--  de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
--  projects.encodedream.tools.Catchitt.main(Catchitt.java:27)
-- ]])

-- java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:728)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  de.jstacs.classifiers.differentiableSequenceScoreBased.ScoreClassifier.extractFurtherClassifierInfosFromXML(ScoreClassifier.java:499)
--  de.jstacs.classifiers.differentiableSequenceScoreBased.gendismix.GenDisMixClassifier.extractFurtherClassifierInfosFromXML(GenDisMixClassifier.java:283)
--  de.jstacs.classifiers.AbstractClassifier.fromXML(AbstractClassifier.java:513)
--  de.jstacs.classifiers.AbstractClassifier.<init>(AbstractClassifier.java:123)
--  de.jstacs.classifiers.AbstractScoreBasedClassifier.<init>(AbstractScoreBasedClassifier.java:165)
--  de.jstacs.classifiers.differentiableSequenceScoreBased.ScoreClassifier.<init>(ScoreClassifier.java:151)
--  de.jstacs.classifiers.differentiableSequenceScoreBased.gendismix.GenDisMixClassifier.<init>(GenDisMixClassifier.java:198)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:728)   
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  projects.encodedream.ClassifiersWithInfo.<init>(ClassifiersWithInfo.java:43)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  projects.encodedream.tools.PredictionTool.run(PredictionTool.java:86)
--  de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
--  projects.encodedream.tools.Catchitt.main(Catchitt.java:27)
-- ]])

-- java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:728)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  projects.encodedream.ClassifiersWithInfo.<init>(ClassifiersWithInfo.java:43)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
--  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
--  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
--  de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
--  de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
--  projects.encodedream.tools.PredictionTool.run(PredictionTool.java:86)
--  de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
--  projects.encodedream.tools.Catchitt.main(Catchitt.java:27)
-- ]])
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:755)
        at de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:683)
        at de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:658)
        at de.jstacs.io.XMLParser.extractObjectAndAttributesForTags(XMLParser.java:637)
        at de.jstacs.io.XMLParser.extractObjectForTags(XMLParser.java:600)
        at projects.encodedream.tools.PredictionTool.run(PredictionTool.java:86)
        at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
        at projects.encodedream.tools.Catchitt.main(Catchitt.java:27)

```

**Comment by jgraux** [comment]
Please excuse this oversight. We introduced a new variable into one of the classes (that is not used by Catchitt but other tools), and did not think about loading old instances. Should be fixed in the github code now. You find a binary version of the fix at http://www.jstacs.de/downloads/Catchitt-0.1.3.jar or the Catchitt homepage.
Please note that the JAR now has a version suffix. So, you might need to modify your scripts or rename the JAR after download.
Please let me know if this version works for you.

**Comment by fransua** [comment]
thanks for the quick reply!
This seems to be restored.

**Comment by jgraux** [comment]
OK, thanks.
I will keep this issue open for a couple of days.
I would be grateful if you could inform me (here) in case of any further problems.
