### ISSUE TITLE
Assignment parameter optional does not exist when running GeMoMa with protein sequences

### ISSUE THREAD

**Issue by bennestor** [Jstacs/Jstacs#24]
Hi, I'm trying to run GeMoMa with annotation evidence from other species + protein sequences from my species (extracted from a transcriptome).

```
java -Xms10G -Xmx120G -jar 0_programs/GeMoMa-1.8.jar CLI GeMoMaPipeline threads=16 GeMoMa.Score=ReAlign \
AnnotationFinalizer.r=NO o=true t=../hakea_chr_v2_mask.fa p=true pc=true pgr=true outdir=5_gemoma_out/macadamia_ts2_hp \
s=own i=Nn a=GCF_000365185.1_Chinese_Lotus_1.1_genomic.gff g=GCF_000365185.1_Chinese_Lotus_1.1_genomic.fna \ 
s=own i=At a=GCF_000001735.4_TAIR10.1_genomic.gff g=GCF_000001735.4_TAIR10.1_genomic.fna \
s=own i=Mi a=GCF_013358625.1_SCU_Mint_v3_genomic.gff g=GCF_013358625.1_SCU_Mint_v3_genomic.fna \
s=own i=Ts a=Tspe_v1/Tspe_v1_gemomaannotation.gff g=Tspe_v1/Tspe_v1.fa \
s=pre-extracted c=Trinity_2021_filt_peptides_NRtop1Emb_ids_tr2.fasta
```

Exception in thread "main" java.lang.RuntimeException: Did not finish as intended. de.jstacs.parameters.SimpleParameter$IllegalValueException: Error in parameter(assignment): Parameter not permitted: File <OPTIONAL> does not exist
        at de.jstacs.parameters.FileParameter.setValue(FileParameter.java:305)
        at projects.gemoma.GeMoMaPipeline.run(GeMoMaPipeline.java:1039)
        at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:92)
        at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
        at projects.gemoma.GeMoMa.main(GeMoMa.java:385)
        
        
I get this error only when I include the last line with the protein sequence fasta. I assume the error is to do with the assignment parameter, but I thought this was optional and I'm not sure how to make the assignment file.

**Comment by bennestor** [comment]
Thank you that solved the problem
