### ISSUE TITLE
Format of search results for GeMoMa s= ?

### ISSUE THREAD

**Issue by xiekunwhy** [Jstacs/Jstacs#28]
Hi,

I use mmseqs results(default format) as search results for GeMoMa, but I got the following errors, why?
java -jar GeMoMa-1.8.jar CLI GeMoMa s=duck.blast ...

Problem while gene: gene-FBXW7_
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Please check the search algorithm input. It seems to have less columns than expected.
line: gene-FBXW7_16	scaffold_4	0.979	147	1	0	1	49	45179652	45179506	9.783E-26	103
split: [gene-FBXW7_16, scaffold_4, 0.979, 147, 1, 0, 1, 49, 45179652, 45179506, 9.783E-26, 103]
original message: 13

	at projects.gemoma.GeMoMa.addHit(GeMoMa.java:1176)
	at projects.gemoma.GeMoMa.run(GeMoMa.java:1003)
	at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:92)
	at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
	at projects.gemoma.GeMoMa.main(GeMoMa.java:385)

here is the duck.blast format
![image](https://user-images.githubusercontent.com/17738229/160329945-415d72ce-c62e-4272-9db3-3ffa8bc79557.png)

Best,
Kun

**Comment by JensKeilwagen** [comment]
Hi Kun,

Thanks a lot for your interest in GeMoMa.
You state that you have an error using "mmseqs results(default format)".
If you you mmseqs the results need to be reformated using the mmseqs module convertalis.
An example is given in the run.sh.

best regards, Jens
