### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.createBindings()" because "engine" is null

### ISSUE THREAD

**Issue by liuningyawen** [Jstacs/Jstacs#35]
Hi Jens,

    Thank you for developing such great software! I try to use GeMoMa to annotate my genome with 5 reference species from Ensembl. But after running for a several hours, I encountered this error report

```
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.createBindings()" because "engine" is null
        at projects.gemoma.Tools.eval(Tools.java:698)
        at projects.gemoma.Tools.filter(Tools.java:731)
        at projects.gemoma.GeMoMaAnnotationFilter.run(GeMoMaAnnotationFilter.java:555)
        at projects.gemoma.GeMoMaPipeline$JGAF.doJob(GeMoMaPipeline.java:2126)
        at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1375)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1660)
        at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1464)
        at projects.gemoma.GeMoMaPipeline$1.run(GeMoMaPipeline.java:609)
        at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1409)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

Statistics:
Job     WAITING RUNNING INTERRUPTED     FAILED  SUCCEEDED
---------------------------------------------------------
MmseqsCreateDB  0       0       0       0       1
EREAndFill      0       0       0       0       1
ExtractorAndSplit       0       0       0       0       5
Mmseqs  0       0       0       0       5
GeMoMa  0       0       0       0       200
Cat     0       0       0       0       5
GAF     0       0       0       1       0

1 jobs did not finish as expected. Please check the output carefully.
Did not delete temporary files allowing to debug.

Elapsed time: 23863 seconds     (6h 37m 43s)
Exception in thread "main" java.lang.RuntimeException: Did not finish as intended. java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.createBindings()" because "engine" is null
        at projects.gemoma.Tools.eval(Tools.java:698)
        at projects.gemoma.Tools.filter(Tools.java:731)
        at projects.gemoma.GeMoMaAnnotationFilter.run(GeMoMaAnnotationFilter.java:555)
        at projects.gemoma.GeMoMaPipeline$JGAF.doJob(GeMoMaPipeline.java:2126)
        at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1375)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

And this is command to run GeMoMa
```
java -jar -Xmx490G /gpfs/home/liunyw/biosoft/GeMoMa/GeMoMa-1.9.jar CLI GeMoMaPipeline threads=40 \
        outdir=/gpfs/home/liunyw/howler_monkey/05.gene-annotation/homology-based/GeMoMa/aloCar/out\
        GeMoMa.Score=ReAlign \
        AnnotationFinalizer.r=NO o=true p=false \
        t=aloCar.masked.fa \
        s=own i=human a=../data_for_annotation/Homo_sapiens.GRCh38.107.chr.gff3 g=../data_for_annotation/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa \
        s=own i=champ a=../data_for_annotation/Pan_troglodytes.Pan_tro_3.0.107.chr.gff3 g=../data_for_annotation/Pan_troglodytes.Pan_tro_3.0.dna_sm.toplevel.fa \
        s=own i=goril a=../data_for_annotation/Gorilla_gorilla.gorGor4.107.chr.gff3 g=../data_for_annotation/Gorilla_gorilla.gorGor4.dna_sm.toplevel.fa \
        s=own i=macac a=../data_for_annotation/Macaca_mulatta.Mmul_10.107.chr.gff3 g=../data_for_annotation/Macaca_mulatta.Mmul_10.dna_sm.toplevel.fa \
        s=own i=mouse a=../data_for_annotation/Mus_musculus.GRCm39.107.chr.gff3 g=../data_for_annotation/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa
```

Can you help me fix this error?

Thanks
Yawen

**Comment by JensKeilwagen** [comment]
Hi Yawen,

I think the problem could be related to the Java version used. What java version are you using?

Nashorn was removed from Java since JDK 15:
https://en.wikipedia.org/wiki/Nashorn_(JavaScript_engine)

So if you're using a newer java version, you need to downgrade Java.

Please let me know if this helps.

best regards, Jens

**Comment by JensKeilwagen** [comment]
You might use the parameter restart to continue the run and save runtime (because mmseqs and GeMoMa steps do not need to computed again)

**Comment by liuningyawen** [comment]
Hi Jens,

Thank you for your reply!

Before I used java18 to run GeMoMa, now I have lowered the version of java. But, I delet the result with java18.
And everything seems to be fine now with lower java version.

Thank  you very much!
Yawen

**Comment by liuningyawen** [comment]
Hi Jens,

After using the Java 11, the GeMoMa is running successfully. 

Thanks for your help and developing the great software!

Yawen
