### ISSUE TITLE
amino acid J found in input

### ISSUE THREAD

**Issue by JohnsonStev** [Jstacs/Jstacs#37]
Hello I used the following gemoma command for gene prediction several times and it always did an excellent job.

java -Xms5G -Xmx150G -jar /project/bat_analysis/baiwei/software/GeMoMa-1.8.jar CLI GeMoMaPipeline \
 threads=40 outdir=annotation_out GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=$genome \
 s=own i=whale a=genomic.gff g=genome.fa \
 GeMoMa.m=100000 

I used the exact command and reference species on another genome but these time it produces errors like this:

GeMoMa for species 0 split=29 throws an Exception
de.jstacs.data.WrongAlphabetException: Symbol "J" from input not defined in alphabet: [A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, V, B, Z, X, *]
	at de.jstacs.data.alphabets.DiscreteAlphabet.getCode(DiscreteAlphabet.java:288)
	at de.jstacs.data.AlphabetContainer.getCode(AlphabetContainer.java:643)
	at de.jstacs.data.sequences.ByteSequence.<init>(ByteSequence.java:159)
	at de.jstacs.data.sequences.ByteSequence.<init>(ByteSequence.java:127)
	at de.jstacs.data.sequences.Sequence.create(Sequence.java:643)
	at de.jstacs.data.sequences.Sequence.create(Sequence.java:611)
	at de.jstacs.data.sequences.Sequence.create(Sequence.java:584)
	at projects.gemoma.GeMoMa.addHit(GeMoMa.java:1192)
	at projects.gemoma.GeMoMa.run(GeMoMa.java:1003)
	at projects.gemoma.GeMoMaPipeline$JGeMoMa.doJob(GeMoMaPipeline.java:1976)
	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1370)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by JensKeilwagen** [comment]
Hi,

Please check the old issue:
https://github.com/Jstacs/Jstacs/issues/14

The current release contains the parameter for replacing unknowns.

best regards, Jens
