### ISSUE TITLE
Problem when adding external evidence

### ISSUE THREAD

**Issue by V-JJ** [Jstacs/Jstacs#43]
Hello!

I've tried to run the whole GeMoMa pipeline for a couple of times. I was able to run it using the evidence from one reference species (obtained with BRAKER). However, when I try to include some `extenal` gff evidence (BRAKER output), something fails. 
I looked throught the issues but still I don't know what happens. 
- May there be any restrictions of the **ID** name or something?

Here you have the error, the code, and one example of the external gff for my target species.

- Error
```

Check RNA-seq data (introns): 31% of the sequences in the reference genome are covered.
Did not delete temporary files allowing to debug.

Exception in thread "main" java.lang.RuntimeException: Did not finish as intended. java.lang.NullPointerException: null
        at projects.gemoma.GeMoMaPipeline.run(GeMoMaPipeline.java:1038)
        at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:94)
        at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
        at projects.gemoma.GeMoMa.main(GeMoMa.java:399)
```

- Command

```
GeMoMa GeMoMaPipeline  \
        threads=$ncpu outdir=$outdir \
        tblastn=false \
        restart=true \
        -Xms200G -Xmx400G \
        GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true \
        t=$target_genome \
        p=true pc=true pgr=true \
        s=own i=Dtil a=$ref_annot g=$ref_genome \
        r=MAPPED ERE.m=$mapped_reads \
        ID=DcatBRp24 e=$ext_annot
date
```

- External GFF

```
ctg620  AUGUSTUS        gene    1806    11524   .       +       .       ID=jg39146;
ctg620  AUGUSTUS        mRNA    1806    11524   .       +       .       ID=jg39146.t1;Parent=jg39146;
ctg620  AUGUSTUS        CDS     1806    2001    0.75    +       2       ID=jg39146.t1.CDS1;Parent=jg39146.t1;
ctg620  AUGUSTUS        exon    1806    2001    .       +       .       ID=jg39146.t1.exon1;Parent=jg39146.t1;
ctg620  AUGUSTUS        intron  2002    2339    .       +       .       ID=jg39146.t1.intron1;Parent=jg39146.t1;
ctg620  AUGUSTUS        CDS     2340    3849    0.77    +       1       ID=jg39146.t1.CDS2;Parent=jg39146.t1;
ctg620  AUGUSTUS        exon    2340    3849    .       +       .       ID=jg39146.t1.exon2;Parent=jg39146.t1;
ctg620  AUGUSTUS        intron  3850    11428   .       +       .       ID=jg39146.t1.intron2;Parent=jg39146.t1;
ctg620  AUGUSTUS        CDS     11429   11524   0.53    +       0       ID=jg39146.t1.CDS3;Parent=jg39146.t1;
ctg620  AUGUSTUS        exon    11429   11524   .       +       .       ID=jg39146.t1.exon3;Parent=jg39146.t1;
ctg620  AUGUSTUS        stop_codon      11522   11524   .       +       0       ID=jg39146.t1.stop1;Parent=jg39146.t1;
ctg1420 AUGUSTUS        gene    1625453 1627745 .       -       .       ID=jg38264;
ctg1420 AUGUSTUS        mRNA    1625453 1627745 .       -       .       ID=jg38264.t1;Parent=jg38264;
ctg1420 AUGUSTUS        stop_codon      1625453 1625455 .       -       0       ID=jg38264.t1.stop1;Parent=jg38264.t1;
ctg1420 AUGUSTUS        CDS     1625453 1625999 0.96    -       1       ID=jg38264.t1.CDS1;Parent=jg38264.t1;
ctg1420 AUGUSTUS        exon    1625453 1625999 .       -       .       ID=jg38264.t1.exon1;Parent=jg38264.t1;
ctg1420 AUGUSTUS        intron  1626000 1627731 .       -       .       ID=jg38264.t1.intron1;Parent=jg38264.t1;
ctg1420 AUGUSTUS        CDS     1627732 1627745 0.2     -       0       ID=jg38264.t1.CDS2;Parent=jg38264.t1;
ctg1420 AUGUSTUS        exon    1627732 1627745 .       -       .       ID=jg38264.t1.exon2;Parent=jg38264.t1;
ctg1420 AUGUSTUS        start_codon     1627743 1627745 .       -       0       ID=jg38264.t1.start1;Parent=jg38264.t1;
Scaffold_2      AUGUSTUS        gene    747379997       747380596       .       -       .       ID=jg51762;
Scaffold_2      AUGUSTUS        mRNA    747379997       747380596       .       -       .       ID=jg51762.t1;Parent=jg51762;
Scaffold_2      AUGUSTUS        stop_codon      747379997       747379999       .       -       0       ID=jg51762.t1.stop1;Parent=jg51762.t1;
Scaffold_2      AUGUSTUS        CDS     747379997       747380596       1       -       0       ID=jg51762.t1.CDS1;Parent=jg51762.t1;
Scaffold_2      AUGUSTUS        exon    747379997       747380596       .       -       .       ID=jg51762.t1.exon1;Parent=jg51762.t1;
Scaffold_2      AUGUSTUS        start_codon     747380594       747380596       .       -       0       ID=jg51762.t1.start1;Parent=jg51762.t1;
Scaffold_5      AUGUSTUS        gene    244344569       244361688       .       -       .       ID=jg4123;
Scaffold_5      AUGUSTUS        mRNA    244344569       244361688       .       -       .       ID=jg4123.t1;Parent=jg4123;
Scaffold_5      AUGUSTUS        stop_codon      244344569       244344571       .       -       0       ID=jg4123.t1.stop1;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        CDS     244344569       244344708       0.93    -       2       ID=jg4123.t1.CDS1;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        exon    244344569       244344708       .       -       .       ID=jg4123.t1.exon1;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        intron  244344709       244346581       .       -       .       ID=jg4123.t1.intron1;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        CDS     244346582       244346629       1       -       2       ID=jg4123.t1.CDS2;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        exon    244346582       244346629       .       -       .       ID=jg4123.t1.exon2;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        intron  244346630       244355368       .       -       .       ID=jg4123.t1.intron2;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        CDS     244355369       244355416       1       -       2       ID=jg4123.t1.CDS3;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        exon    244355369       244355416       .       -       .       ID=jg4123.t1.exon3;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        intron  244355417       244361513       .       -       .       ID=jg4123.t1.intron3;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        CDS     244361514       244361573       1       -       2       ID=jg4123.t1.CDS4;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        exon    244361514       244361573       .       -       .       ID=jg4123.t1.exon4;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        intron  244361574       244361657       .       -       .       ID=jg4123.t1.intron4;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        CDS     244361658       244361688       0.98    -       0       ID=jg4123.t1.CDS5;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        exon    244361658       244361688       .       -       .       ID=jg4123.t1.exon5;Parent=jg4123.t1;
Scaffold_5      AUGUSTUS        start_codon     244361686       244361688       .       -       0       ID=jg4123.t1.start1;Parent=jg4123.t1;
```

Any suggestions are welcome :)
Thanks in advance,

**Comment by JensKeilwagen** [comment]
Hi Vadim,

thanks a lot for your interest in GeMoMa.
I checked your example, but did not see an obvious problem. The ID should not be the problem.
However, I'm wondering why you're using `restart=true`.
Does it successfully run without the external annotation?

`Check RNA-seq data (introns): 31% of the sequences in the reference genome are covered.`
should be a warning and not an error.

Basically, it's a NullPointerException (`java.lang.NullPointerException: null`).

However, the line numbers of the code are different to those in my current version. Hence, could you please provide a minimal example reproducing the error. I'll try to solve the problem.

best regards, Jens

**Comment by V-JJ** [comment]
Hello!

Thanks for the fast reply!

**(1) Does it successfully run without the external annotation?**
- Yes. I was able to run it successfully using:
   - Target genome and the corresponding BAM file
   - One reference genome and a reference GFF

Command:

```sh
search_alg=mmseqs
target_genome=target_genome/TARGETgenome.fasta
ref_annot=ref_genome/augustus.hints.gff3
ref_genome=ref_genome/REFgenome.fasta
threads=20
outdir=GMMresults
lib_type=FR_UNSTRANDED
mapped_reads=Aligned.sortedByCoord.out.bam


$HOME/Programs_V/GeMoMa_1.9/pipeline.sh $search_alg $target_genome $ref_annot \
        $ref_genome $threads $outdir \
        $lib_type $mapped_reads
```


Output files
```
exons.txt
final_annotation.gff
genes.txt
predicted_proteins.fasta
protocol_GeMoMaPipeline.txt
reference_gene_table.tabular
```

**(2) However, I'm wondering why you're using restart=true.**
- Because it seems that everything is ok (when looking at stdout file) of the job that includes the _external evidence_ for my target genome. But no output directory was generated with this run.
- In fact, the Gemoma generated temp directory (**GeMoMa_temp**) contains `final_annotation.gff` file. This is the only result that I can see now.


Short Output message:
```
Statistics:
Job     WAITING RUNNING INTERRUPTED     FAILED  SUCCEEDED
---------------------------------------------------------
MmseqsCreateDB  0       0       0       0       1
EREAndFill      0       0       0       0       1
ExtractorAndSplit       0       0       0       0       1
Mmseqs  0       0       0       0       1
GeMoMa  0       0       0       0       16
Cat     0       0       0       0       1
AnnotationEvidence      0       0       0       0       1
GAF     0       0       0       0       1
AnnotationFinalizer     0       0       0       0       1
```

Complete Output message:

```
/users-d3/vadim.pisarenco/anaconda3/envs/GMM19/bin/GeMoMa
Sun Mar 12 22:59:37 CET 2023
Searching for the new GeMoMa updates ...
Could not connect to the GeMoMa-Homepage. Please check manually at https://www.jstacs.de/index.php/GeMoMa

run new GeMoMaPipeline job
Running the GeMoMaPipeline with 16 threads

search algorithm:

starting phase 1 (1.053s)
=========================
Starting: mmseqs createDB (1.055s)
Starting: Extractor for species 0 (Dtil) (1.056s)
Starting: EREAndFill (1.056s)
starting ERE
Extractor log for species 0 (Dtil):

genes   23202
identical CDS of same gene      0
transcripts     24067

reasons for discarding transcripts:
ambiguous nucleotide    0
start phase not zero    147
missing start   100
missing stop    133
premature stop  56
no DNA  0
wrong phase     0
conflicting phase       0
not linear      0

unexpected error        0

repaired        0

discarded transcript IDs: jg566.t1, jg666.t1, jg782.t1, jg1155.t1, jg1202.t1

Finished: Extractor for species 0 (Dtil) (25.708s)
Finished: mmseqs createDB (91.895s)
starting Denoise
Finished: EREAndFill (924.974s)
genome parts: 4991      [ctg5442_VPextra, ctg4931_VPextra, ctg6171_VPextra, ctg1425_VPextra, ctg2269_VPextra, ctg4604_VPextra, ctg1581_VPextra, Scaffold_3908, Scaffold_3907, Scaffold_3906, Scaffold_3905, Scaffold_3904, Scaff...
possible introns from RNA-seq (split reads>=1): 207101
+: 77017
-: 78898
.: 25593

starting phase 2 (952.077s)
===========================
Starting: mmseqs for species 0 (Dtil) (952.08s)
Finished: mmseqs for species 0 (Dtil) (3653.887s)
Starting: GeMoMa split=0 for species 0 (Dtil) (3684.201s)
Starting: GeMoMa split=4 for species 0 (Dtil) (3684.202s)
[...]
Finished: GeMoMa split=1 for species 0 (Dtil) (7668.149s)
Finished: GeMoMa split=13 for species 0 (Dtil) (14373.532s)

time-out warning:
species 0 (0 (Dtil)): jg10203.t1, jg3225.t1, jg2466.t1, jg8030.t1


starting phase 3 (14373.532s)
=============================
Starting: cat for species 0 (Dtil) (14373.533s)
Starting: AnnotationEvidence for external annotation 0 (14373.533s)
Finished: cat for species 0 (Dtil) (14375.284s)
Finished: AnnotationEvidence for external annotation 0 (14379.451s)

starting phase 4 (14379.451s)
=============================
Starting: GAF (14379.451s)
species 0
species 1
Delete attributes in evidence file 1: 56877 "Parent"
all: 138921
filtered: 91119
clustered: 59382

genes: 63488
transcripts: 66468

        genes   genes with maxTie=1     transcripts     transcripts with tie=1  transcripts with tie=NA, tpc=1
(max)evidence=1 59462   5162    62432   6617    1746
(max)evidence=2 4026    1462    4036    1466    866

input   filtered transcripts    final transcripts supported     final genes supported
input 0 39622   28947   28112
input 1 55535   41557   41314
Finished: GAF (14417.475s)

starting phase 5 (14417.476s)
=============================
Starting: AnnotationFinalizer (14417.476s)
genome parts: 4991      [ctg5442, ctg4931, ctg6171_x, ctg1425_x2...

#genes: 63488
#warnings: [0, 0]
#mRNAs: 66468
#warnings: [0, 0]
#CDSs: 232585
#warnings: [0, 0]

#transcripts with 5'-UTR annotation: 0
#transcripts with 3'-UTR annotation: 0
#transcripts with some UTR annotation: 0
#transcripts with 5'- and 3'-UTR annotation: 0
Finished: AnnotationFinalizer (14429.854s)

Statistics:
Job     WAITING RUNNING INTERRUPTED     FAILED  SUCCEEDED
---------------------------------------------------------
MmseqsCreateDB  0       0       0       0       1
EREAndFill      0       0       0       0       1
ExtractorAndSplit       0       0       0       0       1
Mmseqs  0       0       0       0       1
GeMoMa  0       0       0       0       16
Cat     0       0       0       0       1
AnnotationEvidence      0       0       0       0       1
GAF     0       0       0       0       1
AnnotationFinalizer     0       0       0       0       1

```

I'll try to make an example that gives the same error.

Thanks!

**Comment by V-JJ** [comment]
**Update**

- I looked through the issues and found out that "synteny check" may cause some trouble (#21). 
- It seems that this have partially solved my problem. With this command (below), I was able to obtain the results without any error. BUT, the output directory contained only these files. Does this make sense?
```
external_annotation_0_with_evidence.gff
protocol_GeMoMaPipeline.txt
unfiltered_predictions_from_species_0.gff
```

Now I'm trying to run the whole pipeline once again using `debug=false` as well since after the (apparently) successful run, the content of `GeMoMa_temp` dir has been removed.

```
GeMoMa GeMoMaPipeline  \
        threads=$ncpu outdir=$outdir \
        tblastn=false \
        restart=true \
        -Xms200G -Xmx400G \
        GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true \
        t=$target_genome \
        p=true pc=true pgr=true \
        s=own i=Dtil a=$ref_annot g=$ref_genome \
        r=MAPPED ERE.m=$mapped_reads \
        ID=DcatBRp24 e=$ext_annot \
        sc=false \
        debug=false
```

**Comment by JensKeilwagen** [comment]
Hi Vadim,

thanks for the update. It's interesting to see that SyntenyChecker still seems to be a problem. I would like to have more information about the problem. Hence, it would be good to have minimal example and the full information about the version and the output (complete protocol).

Regarding your output, it seems that the final annotation is missing. Again, could you please provide the complete protocol and a minimal example?

best reagrds, Jens

**Comment by V-JJ** [comment]
Hello! 

Sorry for the late response. I have managed to solve the issues by running the whole pipeline step by step. Apparently, there was an issue with my gff used as "external evidence" for my "target genome". I solved it by pre-processing it with `AnnotationEvidence` 

Thanks again!
