### ISSUE TITLE
Could not open GeMoMa_temp/GeMoMaPipeline-9364982901453846136/mmseqsdb_h.index.5 for writing!

### ISSUE THREAD

**Issue by sjfleck** [Jstacs/Jstacs#48]
Thanks for creating GeMoMa. I've been using GeMoMa for a long time, but my university updated their hardware and we need to reinstall GeMoMa. There was no EasyBuild (new system they want us to use) to install jstacs or GeMoMa, so I decided to install Miniconda and install GeMoMa-1.9 as a conda environment. It seemed to work just fine, but I couldn't get it to run. After reading through the issues, I tried running chmod -R 777 on the conda environment and it had an effect. Now when I run GeMoMa, I get a new error: 

[mmseqs]: 14.7e284
[mmseqs]: Could not open GeMoMa_temp/GeMoMaPipeline-9364982901453846136/mmseqsdb_h.index.5 for writing!
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
	at projects.gemoma.GeMoMaPipeline$1.run(GeMoMaPipeline.java:609)
	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1409)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
No gene model was extracted from the references.
8 jobs did not finish as expected. Please check the output carefully.
Did not delete temporary files allowing to debug.

when I cd into GeMoMaPipeline-9364982901453846136, these files exist:
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.0
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.1
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.2
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.3
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.4
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.5
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.index.0
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.index.1
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.index.2
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.index.3
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb_h.index.4
-rw-rw-r-- 1 sjfleck grp-vaalbert      0 Oct 27 13:27 mmseqsdb.source
-rw-rw-r-- 1 sjfleck grp-vaalbert 206561 Oct 27 13:27 parameters.xml

do you have any ideas as to why this error is happening? Why can it make mmseqsdb_h.index.4, but not mmseqsdb_h.index.5? Thanks,
Steve

**Comment by sjfleck** [comment]
for anyone else with this issue. I was a simple solution. I ran it in one of our allocations that had reached its file number limit. when I tried running it in a different allocation that didn't reach its file number limit, it ran without an issue.

**Comment by JensKeilwagen** [comment]
Hi Steve,

sorry, I had a long holiday weekend in Germany and just read your issue. Great that you solved it.

best regards, Jens
