### ISSUE TITLE
java.lang.InterruptedException

### ISSUE THREAD

**Issue by xiongqian123456789** [Jstacs/Jstacs#50]
Hello! 
I used GeMoma by with given external annotation external.gff, the command is as follows:

java -jar /newlustre/home/xiongqian/software/annotation/gemoma/GeMoMa-1.9.jar CLI GeMoMaPipeline threads=24 tblastn=false GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=D2005012427.Euk.IDs.fa outdir=test s=own i=1 a=GCA_000143455.1.gff g=GCA_000143455.1.fas  s=own i=2 a=GCA_001584585.1.gff g=GCA_001584585.1.fas  s=own i=3 a=GCA_030144725.1.gff g=GCA_030144725.1.fas s=own i=4 a=GCA_030272155.1.gff g=GCA_030272155.1.fas ID=august e=D2005012427.augustus.gff3

And get the error is：
Problem while gene: gene-QJQ45_015695_
GeMoMa for species 2 (3) split=20 throws an Exception
java.lang.Exception: Forwarding java.lang.OutOfMemoryError: Java heap space
        at de.jstacs.algorithms.alignment.Alignment.computeAlignment(Alignment.java:248)
        at projects.gemoma.GeMoMa$MyAlignment.computeAlignment(GeMoMa.java:4707)
        at de.jstacs.algorithms.alignment.Alignment.getAlignment(Alignment.java:185)
        at de.jstacs.algorithms.alignment.Alignment.getAlignment(Alignment.java:167)
        at projects.gemoma.GeMoMa$TranscriptPredictor.computeTranscript(GeMoMa.java:2636)
        at projects.gemoma.GeMoMa$TranscriptPredictor.compute(GeMoMa.java:2336)
        at projects.gemoma.GeMoMa.run(GeMoMa.java:1012)
        at projects.gemoma.GeMoMaPipeline$JGeMoMa.doJob(GeMoMaPipeline.java:1988)
        at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1375)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

GeMoMa for species 2 (3) split=16 throws an Exception
GeMoMa for species 2 (3) split=7 throws an Exception
GeMoMa for species 2 (3) split=10 throws an Exception
GeMoMa for species 2 (3) split=14 throws an Exception

Really apprieciated for your help! 

- [ ]

**Comment by JensKeilwagen** [comment]
Please check the answer in https://github.com/Jstacs/Jstacs/issues/49
