### ISSUE TITLE
Error: Prefilter died

### ISSUE THREAD

**Issue by Wanjie-Feng** [Jstacs/Jstacs#63]
Hello ! 
Thank you very much for developing such a good tool ! A lot of help to me ! 
I encountered some trouble when using this tool, mainly the problem of algorithm software settings. When I set to use tblastn ( tblastn = true ), everything runs normally, but I think the running speed is too slow ( my genome is 500M, I used 10 annotation files of related species and 66 RNA-seq bam files ), but when I want to use mmseqs ( tblastn = false ), there are always problems :
```
..............................
Finished: Extractor for species 3 (Vicia) (129.349s)
starting Denoise
Finished: EREAndFill (2059.348s)
genome parts: 1	[Chr1]
possible introns from RNA-seq (split reads>=1): 29520
+: 13290
-: 13476
.: 1377

starting phase 2 (2064.737s)
============================
Starting: mmseqs for species 0 (Wm82NJAU) (2064.754s)
[mmseqs]: Segmentation fault (core dumped)
[mmseqs]: Error: Prefilter died
[mmseqs]: Error: Search step died
Finished: mmseqs for species 0 (Wm82NJAU) (2114.245s)
Starting: mmseqs for species 1 (Gsoja) (2114.255s)
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
	at projects.gemoma.GeMoMaPipeline$1.run(GeMoMaPipeline.java:609)
	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1409)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.InterruptedException

Statistics:
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)Job
	WAITING	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
	RUNNING	INTERRUPTED	at projects.gemoma.GeMoMaPipeline$1.run(GeMoMaPipeline.java:609)	FAILED	SUCCEEDED

	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1409)
---------------------------------------------------------
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)MmseqsCreateDB
	0	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	0	0	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	0	1	at java.base/java.lang.Thread.run(Thread.java:829)

java.lang.InterruptedExceptionEREAndFill	0	0
	0	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
	0	1	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)

	at projects.gemoma.GeMoMaPipeline$1.run(GeMoMaPipeline.java:609)
ExtractorAndSplit	0	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1409)
	0	0	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	0	10	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Mmseqs	8	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	1	0	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	1	0	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

.......................

```
My sample code is:
```
java -jar GeMoMa/GeMoMa-1.9.jar CLI GeMoMaPipeline \
threads=50 \
outdir=./result \
GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true \
AnnotationFinalizer.u=YES AnnotationFinalizer.a=prime \
t=Chr1-2.fa \
s=own i=Wm82NJAU a=/Wm82-NJAU/Wm82-NJAU.gff.gz g=/Wm82-NJAU/Wm82-NJAU.fasta.gz \
s=own i=Gsoja a=/Glycine_soja/Glycine_soja.ASM419377v2.59.gff3.gz g=/Glycine_soja/Glycine_soja.ASM419377v2.dna.toplevel.fa.gz \
s=own i=Phaseolusvulgaris a=/Phaseolus_vulgaris/Phaseolus_vulgaris.PhaVulg1_0.59.gff3.gz g=/Phaseolus_vulgaris/Phaseolus_vulgaris.PhaVulg1_0.dna.toplevel.fa.gz \
s=own i=Vicia a=/Vicia_faba_Hedin2/Vicia_faba.Hedin2_genome_v1.59.gff3.gz g=/Vicia_faba_Hedin2/Vicia_faba.Hedin2_genome_v1.dna.toplevel.fa.gz \
s=own i=Vigna a=/Vigna_angularis/Vigna_angularis.Vigan1.1.59.gff3.gz g=/Vigna_angularis/Vigna_angularis.Vigan1.1.dna.toplevel.fa.gz \
s=own i=Vignaradiata a=/Vigna_radiata/Vigna_radiata.Vradiata_ver6.59.gff3.gz g=/Vigna_radiata/Vigna_radiata.Vradiata_ver6.dna.toplevel.fa.gz \
s=own i=CAAS a=/CAAS_Psat_ZW6_1.0/GCF_024323335.1/genomic.gff.gz g=/CAAS_Psat_ZW6_1.0/GCF_024323335.1/GCF_024323335.1_CAAS_Psat_ZW6_1.0_genomic.fna.gz \
s=own i=peanut a=/peanut/GCF_003086295.2/genomic.gff.gz g=/peanut/GCF_003086295.2/GCF_003086295.2_arahy.Tifrunner.gnm1.KYV3_genomic.fna.gz \
s=own i=Medicago a=/Medicago_truncatula/Medicago_truncatula.MedtrA17_4.0.59.gff3.gz g=/Medicago_truncatula/Medicago_truncatula.MedtrA17_4.0.dna.toplevel.fa.gz \
s=own i=Pisum a=/Pisum_sativum_v1a/Pisum_sativum_v1a_genes.gff3.gz g=/Pisum_sativum_v1a/Pisum_sativum_v1a.fa.gz \
r=MAPPED \
ERE.m=/singleChr/Viciabaicalensis_AG625-01-T66_good_Chr1.sorted.bam  \
ERE.m=/singleChr/Viciabaicalensis_AG625-01-T55_good_Chr1.sorted.bam  \
ERE.m=/singleChr/Viciabaicalensis_AG625-01-T58_good_Chr1.sorted.bam  \
ERE.m=/singleChr/Viciabaicalensis_AG625-01-T02_good_Chr1.sorted.bam  ERE.c=true
```

**Comment by JensKeilwagen** [comment]
Hi Wanjie-Feng,

Thanks a lot for using GeMoMa.
It seems that this is a mmseqs error and more or less unrelated to GeMoMa.
I googled and found:
https://github.com/soedinglab/MMseqs2/issues/234
Which version of mmseqs are you using? 

best regards, Jens

**Comment by Wanjie-Feng** [comment]
Thanks for your prompt reply!
The version number of my mmseqs is:
```
MMseqs2 Version: 15.6f452
© Martin Steinegger (martin.steinegger@snu.ac.kr)
```
I installed mmseqs through conda:
```
conda install bioconda::mmseqs2
```
I did realize that this was an mmseqs error, but I did not find the appropriate solution, and I also ran the GeMoMa sample data and reported the same error

**Comment by JensKeilwagen** [comment]
I just checked: There are some bug reports for mmseqs with search phrase "prefilter died" in the last days:
https://github.com/soedinglab/MMseqs2/issues?q=is%3Aissue+is%3Aopen+%22prefilter+died%22

They state one should test the latest version of mmseqs (16-747c6 https://github.com/soedinglab/MMseqs2/releases/tag/16-747c6). If this does not fix the problem, we might need to make a bug report for mmseqs.

Please keep me updated.

best regards, Jens

**Comment by Wanjie-Feng** [comment]
What should I do now? If mmseqs is temporarily unavailable, is there any way to speed up tblastn when I was running it with 150 threads

**Comment by JensKeilwagen** [comment]
I would recommend to
1) Check whether the latest version of mmseqs solves the problem. If not

2a) Check whether an older version of mmseqs works. If just looked in some old protocols and found that mmseqs version 13.45111 worked well. You might test that first.
2b) Make a bug for mmseqs.

I have to admit that I haven't used tblastn in GeMoMa for a long time.

**Comment by Wanjie-Feng** [comment]
Ok, I see. Thank you for your advice,

**Comment by JensKeilwagen** [comment]
Please keep me updated

**Comment by Wanjie-Feng** [comment]
OK，I will

**Comment by Wanjie-Feng** [comment]
Hello!
I tested the latest version of mmseqs, but it still doesn't work. Then I used the specific version you recommended, and now there seems to be no problem. However, I reported the following errors in the following steps, which I guess is the problem of my java version, so I replaced the earlier version of Java.
```
starting phase 3 (19270.958s)
=============================
No external annotation given.
Starting: cat for species 0 (Wm82NJAU) (19270.959s)
Starting: cat for species 1 (Gsoja) (19270.96s)
Finished: cat for species 1 (Gsoja) (19284.311s)
Finished: cat for species 0 (Wm82NJAU) (19287.597s)

starting phase 4 (19287.598s)
=============================
Starting: GAF (19287.608s)
species 0
species 1
all: 932515
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.createBindings()" because "engine" is null
	at projects.gemoma.Tools.eval(Tools.java:698)
	at projects.gemoma.Tools.filter(Tools.java:731)
	at projects.gemoma.GeMoMaAnnotationFilter.run(GeMoMaAnnotationFilter.java:555)
	at projects.gemoma.GeMoMaPipeline$JGAF.doJob(GeMoMaPipeline.java:2126)
	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1375)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1667)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1464)
	at projects.gemoma.GeMoMaPipeline$1.run(GeMoMaPipeline.java:609)
	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1409)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

Statistics:
Job	WAITING	RUNNING	INTERRUPTED	FAILED	SUCCEEDED
---------------------------------------------------------
MmseqsCreateDB	0	0	0	0	1
EREAndFill	0	0	0	0	1
ExtractorAndSplit	0	0	0	0	2
Mmseqs	0	0	0	0	2
GeMoMa	0	0	0	0	100
Cat	0	0	0	0	2
GAF	0	0	0	1	0

1 jobs did not finish as expected. Please check the output carefully.
Did not delete temporary files allowing to debug.

Elapsed time: 19302 seconds	(5h 21m 42s)
Exception in thread "main" java.lang.RuntimeException: Did not finish as intended. java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.createBindings()" because "engine" is null
	at projects.gemoma.Tools.eval(Tools.java:698)
	at projects.gemoma.Tools.filter(Tools.java:731)
	at projects.gemoma.GeMoMaAnnotationFilter.run(GeMoMaAnnotationFilter.java:555)
	at projects.gemoma.GeMoMaPipeline$JGAF.doJob(GeMoMaPipeline.java:2126)
	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1375)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
The java version number I changed is：

```
openjdk 11.0.25-internal 2024-10-15
OpenJDK Runtime Environment (build 11.0.25-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.25-internal+0-adhoc..src, mixed mode)
```
I want to know how to set up to continue running from where it failed, rerun all steps is too time consuming

**Comment by JensKeilwagen** [comment]
Hi Wanjie-Feng,

Yes, this is a Java version problem.
You can restart the job using restart=true.
http://www.jstacs.de/index.php/GeMoMa-Docs#GeMoMa_pipeline

best regards, Jens

**Comment by Wanjie-Feng** [comment]
I've got it up and running. Thank you very much

**Comment by kuangzhuoran** [comment]
Hi, my command is "java -Xmx120G -jar GeMoMa-1.9.jar CLI GeMoMaPipeline threads=20 t=hap2.softmasked.fa s=own g=GCF_023634155.1.fna a=GCF_023634155.1.longest.gff outdir=result AnnotationFinalizer.r=NO tblastn=false" 
I met a same error.
And I try the earlier version of Java:
openjdk version "11.0.25-internal" 2024-10-15
OpenJDK Runtime Environment (build 11.0.25-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.25-internal+0-adhoc..src, mixed mode)

I also try the latest version of mmseqs:
MMseqs2 Version: 16.747c6

These do not work.

**Comment by kuangzhuoran** [comment]
search algorithm:
[mmseqs]: 16.747c6

starting phase 1 (1.082s)
=========================
Starting: mmseqs createDB (1.085s)
Starting: Extractor for species 0 (1.086s)
Starting: EREAndFill (1.088s)
Finished: EREAndFill (1.088s)
Finished: mmseqs createDB (7.196s)
genome parts: 202       [FCS26, FCS27, FCS24, FCS25, FCS28, FCS29, FCS128, FCS127, FCS129, FCS22, FCS23, FCS20, FCS21, FCS131, FCS130, FCS133, FCS132, FCS135, FCS134, FCS137, FCS136, FCS15, FCS16, FCS13, FCS14, FCS19, FCS17,...

identical CDS of same gene      0
transcripts     15658

reasons for discarding transcripts:
ambiguous nucleotide    0
start phase not zero    12
missing start   98
missing stop    52
premature stop  263
no DNA  0
wrong phase     0
conflicting phase       0
not linear      0

unexpected error        0

repaired        0

discarded transcript IDs: rna-XM_027779841.2, rna-XM_005243568.4......

Finished: Extractor for species 0 (11.047s)

starting phase 2 (11.048s)
==========================
Starting: mmseqs for species 0 (11.049s)
[mmseqs]: Segmentation fault (core dumped)
[mmseqs]: Error: Prefilter died
[mmseqs]: Error: Search step died
Finished: mmseqs for species 0 (102.591s)

Statistics:
Job     WAITING RUNNING INTERRUPTED     FAILED  SUCCEEDED
---------------------------------------------------------
MmseqsCreateDB  0       0       0       0       1
EREAndFill      0       0       0       0       1
ExtractorAndSplit       0       0       0       0       1
Mmseqs  0       0       0       1       0

1 jobs did not finish as expected. Please check the output carefully.
Did not delete temporary files allowing to debug.

Elapsed time: 103 seconds       (0h 1m 43s)
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
        at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
        at projects.gemoma.GeMoMaPipeline$1.run(GeMoMaPipeline.java:609)
        at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1409)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "main" java.lang.RuntimeException: Did not finish as intended. 
        at projects.gemoma.GeMoMaPipeline.run(GeMoMaPipeline.java:1234)
        at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:94)
        at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
        at projects.gemoma.GeMoMa.main(GeMoMa.java:399)

**Comment by kuangzhuoran** [comment]
Well, It may related to run memory.
I add "-Xmx240G", and it works/
![4a3a84edc9c777a2d55e76dc0f14656](https://github.com/user-attachments/assets/485940a5-593e-420d-ac25-d6ce0d4c2dd3)
